<?php

namespace SV\ViewStaffThreads\XF\Finder;

class Thread extends XFCP_Thread
{
	public function applyVisibilityChecksInForum(\XF\Entity\Forum $forum)
	{
		$return = parent::applyVisibilityChecksInForum($forum);
		$visitor = \XF::visitor();

		$sqlConditions = $return->conditions;

		$preparedConditions = array();

		foreach ($sqlConditions AS $key => $condition)
		{
			if (strpos($condition, 'OR (`xf_thread`.`discussion_state` IN (\'visible\'))') !== false)
			{
				$condition = str_replace('OR (`xf_thread`.`discussion_state` IN (\'visible\'))');
			}

			$preparedConditions[] = $condition;
		}
		die(\XF::dump($preparedConditions));

		//

		//$this->resetWhere();

		for($i = count($sqlConditions) - 1; $i >=0; $i--)
		{
			$sqlCondition = $sqlConditions[$i];
			if (strpos($sqlConditions[$i], '`xf_thread`.`user_id`') !== false &&
				strpos($sqlConditions[$i], '`xf_thread`.`discussion_state` = \'moderated\' AND `xf_thread`.`user_id` = ') !== false)
			{
				$parts[] = '`xf_thread`.`sticky` = 1';
				//$parts[] = '`xf_user`.`is_staff` = 1';
/*
				$parts = array();
				if (!empty($conditions['sticky']) && !empty($conditions['viewStickies']))
				{
				}
				if (!empty($conditions['viewStaff']))
				{
				}*/
				if ($parts)
				{
					$sqlConditions[$i] = "({$sqlCondition} OR (`xf_thread`.`discussion_state` = 'visible' AND (". implode(' OR ', $parts) .')))';
				}
				unset($sqlConditions[2]);
				break;
			}
		}

		/*if ($visitor->hasNodePermission($forum->node_id, 'viewStickies'))
		{
			$conditions[] = ['sticky', 1];
		}

		if ($visitor->hasNodePermission($forum->node_id, 'viewStaff'))
		{
			//
		}*/
		foreach ($sqlConditions as $condition)
		{
			$this->whereSql($condition);

		}

		die(\XF::dump($this));

		return $this; // TODO: Change the autogenerated stub
	}
}